language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - '10'
  - '12'
deploy:
  - provider: script
    script: npx nlm release
    skip_cleanup: true
    'on':
      branch: master
      node: '12'
